

image: florianrauscha/gitlab-ci-android-fastlane:latest

stages:
    #- quality_assurance
    - test
    - build


before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - mkdir -p $GRADLE_USER_HOME
    - chmod +x ./gradlew

cache:
    paths:
        - .gradle/wrapper
        - .gradle/caches

#RULES-------------------------------

sdk_build_dev:
    stage: build
    script:
        - ./gradlew :bliink-android-sdk:assembleDebug
    artifacts:
        paths:
            - bliink-android-sdk/build/outputs/
    tags:
        - docker

sample_build_dev:
    stage: build
    script:
        - ./gradlew :bliink-sample:assembleDebug
    artifacts:
        paths:
            - bliink-sample/build/outputs/
    tags:
        - docker

sdk_unit_tests_dev:
    stage: test
    script:
        - ./gradlew :bliink-android-sdk:test
    tags:
        - docker

sample_unit_tests_dev:
    stage: test
    script:
        - ./gradlew :bliink-sample:test
    tags:
        - docker

        #static_analysis:
        #    stage: quality_assurance
        #    script:
        #      - ./gradlew lint
        #      - ./gradlew checkstyle
        #      - ./gradlew pmd
        #      - ./gradlew findbugs
        #    artifacts:
        #      name: "reports_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
        #      when: on_failure
        #      expire_in: 4 days
        #      paths:
        #        - bliink-android-sdk/build/reports/
        #        - bliink-sample/build/reports/
        #    tags:
        #      - docker